### ISSUE TITLE
Installation fails on imoprt golint

### ISSUE THREAD

**Issue by ronna-s** [tehsphinx/exalysis#23]
The package golint has been moved from github.com/golang/lint to golang.org/x/lint, and modules are still not on by default in Go. This means that anyone who doesn't have modules configured gets the following error:
`tehsphinx/exalysis/exam/golint.go:7:2: code in directory [GOPATH]/github.com/golang/lint expects import "golang.org/x/lint".`

**Comment by tehsphinx** [comment]
Would you suggest adding the dependencies to the `vendor` directory for backwards compatibility? Or did you have something else in mind?

I will change the import path to `golang/x/lint`. Thx

**Comment by tehsphinx** [comment]
Note: I removed the `vendor dependencies` commit but the reference does not get removed.

**Comment by tehsphinx** [comment]
Now I have the problem that it does not work with go modules enabled. (see attach PR fails on travis build)

@ronna-s: any ideas?

**Comment by tehsphinx** [comment]
9f5e44659465af0809c0a73a01e40ea1cc423ba0
