### ISSUE TITLE
Hamming: return zero value on error

### ISSUE THREAD

**Issue by liftedkilt** [tehsphinx/exalysis#32]
I noticed that several students have submitted versions where they are returning `-1` alongside the error. This is because they are misreading the test cases, and think that they are required to do so. I also noticed that in the solutions in this repo, solutions 1, and 3-7 are all returning that same value. Would it be more idiomatic to return the zero value in case of an error?

I would propose some variation of the following message be suggested:

---

It is more idiomatic to return the zero value (since it's an `int`, it would be `0`) instead of `-1`. The test cases appear at first glance to be asking for a -1, but if you look at line 10 of hamming_test.go, it's just using a negative `tc.want` value to indicate that there should be _some_ error.

```
if tc.want < 0 {
	// check if err is of error type
	var _ error = err

	// we expect error
	if err == nil {
		t.Fatalf("Distance(%q, %q). error is nil.",
			tc.s1, tc.s2)
	}
...
```

**Comment by bitfield** [comment]
Arguably (and I do so argue) the test code is wrong, for specifying an expected value and then not checking for it. A student who reads the test cases carefully should be commended, not corrected.

The point is it doesn't matter what you return in this case; the presence of an error means the return value is useless, so it can be anything at all. I agree that, since it doesn't matter, zero is the obvious choice, but that being so, we should fix the test cases.

**Comment by tehsphinx** [comment]
I agree, we should fix the tests if they suggest returning `-1`. I sometimes told students to return the `zero` value and think we should add that to exalysis **after** we fixed the tests.

@liftedkilt do you want to make a PR for changing the tests on that exercise? You can do that here: https://github.com/exercism/website-copy. If not, let us know so we can do it.

**Comment by tehsphinx** [comment]
@liftedkilt: Thanks a lot for your contribution! It is really appreciated!

**Comment by liftedkilt** [comment]
@tehsphinx thanks! It actually looks like this was already [fixed](https://github.com/exercism/problem-specifications/pull/875) in the canonical-data.json. Hamming just needs to be regenerated with version 2.1.1

**Comment by tehsphinx** [comment]
Thanks for the update!

That means we can implement a suggestion here...
